IT_Zorro/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts.views import (login_view, register_view, logout_view)
from studentfood.views import (checkEmail)
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('studentfood.urls')),
    path('admin/', admin.site.urls),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('reg/', register_view, name='register'),
    path('check_email/', checkEmail),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

studentfood/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'studentfood'
urlpatterns = [
    path('', views.main, name='main'),
    url(r'^detail/([0-9]{1,3})/$', views.detail, name='detail'),
    url(r'^profile/$', views.profile, name='profile'),
    url(r'^favourite_added/([0-9]{1,3})/$', views.favourite_add, name='favourite_add'),
    url(r'^password_reset/$', views.change_password, name='password_reset'),
    url(r'^change_photo/$', views.change_photo, name='change_photo'),
    url(r'^remove_recipe/([0-9]{1,3})/$', views.remove_recipe, name='remove_recipe'),
    url(r'^remove_password/<int:recipe_id>/$', views.remove_recipe, name='remove_recipe_too')
]

studentfood/models.py
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import AbstractUser

# Create your models here.

# подписать поля


class User(AbstractUser):
    photo = models.ImageField('Фото', default='user_img/no_photo.jpg', upload_to='user_img')  # установлена стандартная фотография. пользовательские фото будут загружены в media/user_img

    def create_recipe(self, recipe_name, description, price, category):  # по идее параметры для функции должны браться
        #  из полей фронта, а потом на их основе выполняется функция создания и привязки рецепта к юзеру
        self.recipe_set.create(recipe_name=recipe_name, description=description, price=price, category=category, pub_date=timezone.now())

    @property
    def photo_url(self):
        if self.photo and hasattr(self.photo, 'url'):
            return self.photo.url


class Recipe(models.Model):  # рецепт
    recipe_name = models.CharField('Название', max_length=40)  # название рецепта
    pub_date = models.DateTimeField('Дата публикации', auto_now_add=True)  # дата публикация
    description = models.TextField('Описание')  # описание рецепта
    price = models.IntegerField('Примерная стоимость', null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    GLOBAL_CATEGORY = [
        ('first', 'Первые блюда'),
        ('second', 'Вторые блюда'),
        ('snack', 'Закуски/Салаты'),
        ('sweet', 'Сладкое/Десерты'),
    ]
    category = models.CharField('Категория', choices=GLOBAL_CATEGORY, max_length=16, blank=True)
    photo = models.ImageField('Фото рецепта', default='recipe_img/no_photo.jpg', null=True, blank=True, upload_to='recipe_img')  # фото будут храниться по пути /media/recipe_img (не забудь создать эти папки перед тестом)
    is_removed = models.BooleanField('Статус удаления', default=False)

    def __str__(self):  # при запросе класса выводит название рецепта
        return self.recipe_name

    @property
    def photo_url(self):
        if self.photo and hasattr(self.photo, 'url'):
            return self.photo.url

    def calculate_mark(self):  # реализовать оценку
        max_marks = self.mark_set.all()
        sum_marks = 0
        for get_mark in max_marks:
            sum_marks += get_mark.mark_value
        if len(max_marks) == 0:
            avg_mark = 0
        else:
            avg_mark = sum_marks/len(max_marks)
        return avg_mark


class Comment(models.Model):
    text = models.CharField('Текст комментария', max_length=1500)
    user = models.ForeignKey(User, on_delete=models.CASCADE)  # связь комментария с пользователем
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)  # связь комментария с рецептом
    pub_date = models.DateTimeField('Опубликовано', default=timezone.now)


class Mark(models.Model):
    USER_MARK_SET = [
        (1, 1),
        (2, 2),
        (3, 3),
        (4, 4),
        (5, 5),
    ]
    mark_value = models.FloatField(choices=USER_MARK_SET, validators=[MinValueValidator(0.0), MaxValueValidator(5.0)])
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        unique_together = ('recipe', 'user')


class BookMark(models.Model):
    added_recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)
    user_added = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        unique_together = ('added_recipe', 'user_added')

studentfood/forms.py
from django import forms
from .models import User, Recipe, Comment, Mark
from django.db import models


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)


class RecipeForm(forms.ModelForm):
    class Meta:
        model = Recipe
        fields = ("recipe_name", "description", "price", "category", "photo")


class ChangePasswordForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ("password",)


class ChangePhotoForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('photo',)


class MarkForm(forms.ModelForm):
    class Meta:
        model = Mark
        fields = ('mark_value',)


class BookMarkForm(forms.ModelForm):
    check = forms.BooleanField()

studentfood/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from .models import Recipe, User, Comment, Mark, BookMark
from .forms import CommentForm, RecipeForm, ChangePasswordForm, MarkForm, ChangePhotoForm
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q
from django.http import JsonResponse


# Create your views here.

def main(request):  # лист рецептов
    search_query = request.GET.get('search', '')
    category_query = request.GET.get('category_button', '')
    null_recipe = Recipe()
    raw_category = null_recipe.GLOBAL_CATEGORY
    site_category = []
    for elem in raw_category:
        site_category.append(elem[1])
    if search_query:
        recipes_list = Recipe.objects.filter(
            Q(recipe_name__icontains=search_query) | Q(description__icontains=search_query))
    elif category_query:
        for raw in raw_category:
            if category_query == raw[1]:
                recipes_list = Recipe.objects.filter(Q(category__exact=raw[0]))
    else:
        recipes_list = Recipe.objects.filter(Q(is_removed=False)).order_by('-pub_date')

    paginator = Paginator(recipes_list, 3)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    try:
        page_obj = paginator.get_page(page_number)
    except PageNotAnInteger:
        page_obj = paginator.get_page(1)
    except EmptyPage:
        page_obj = paginator.get_page(paginator.num_pages)

    context = {'recipes_list': recipes_list,
               'page_obj': page_obj,
               'site_category': site_category
              }
    return render(request, 'studentfood/html/main_page/main.html', context)


def detail(request, recipe_id):  # объект (написать список полей)
    recipe_detail = get_object_or_404(Recipe, pk=recipe_id)
    comment_list = recipe_detail.comment_set.all()
    comments_count = comment_list.count()
    marks_list = recipe_detail.mark_set.all()
    bookmark_list = recipe_detail.bookmark_set.all()
    bookmark_user_ids = []
    for row in bookmark_list:
        bookmark_user_ids.append(row.user_added.id)
    comment_form = CommentForm()
    mark_form = MarkForm()
    post_comment = None
    if request.method == 'POST':
        comment_form = CommentForm(request.POST)
        post_comment = Comment()
        mark_form = MarkForm(request.POST)
        post_mark = Mark()

        if comment_form.is_valid():
            post_comment.text = comment_form.cleaned_data.get("text")
            post_comment.recipe = get_object_or_404(Recipe, pk=recipe_id)
            post_comment.user = request.user
            post_comment.save()
            return redirect('studentfood:detail', recipe_id)

        elif mark_form.is_valid():
            for usr in marks_list:
                if usr.user == request.user:
                    edit_mark = recipe_detail.mark_set.get(user=request.user)
                    edit_mark.mark_value = mark_form.cleaned_data.get('mark_value')
                    edit_mark.save()
                    return redirect('studentfood:detail', recipe_id)
            post_mark.mark_value = mark_form.cleaned_data.get('mark_value')
            post_mark.user = request.user
            post_mark.recipe = get_object_or_404(Recipe, pk=recipe_id)
            post_mark.save()
            return redirect('studentfood:detail', recipe_id)

    context = {'recipe_detail': recipe_detail,
               'comment_list': comment_list,
               'comment_form': comment_form,
               'post_comment': post_comment,
               'comments_count': comments_count,
               'mark_form': mark_form,
               'bookmark_user_ids': bookmark_user_ids
              }

    return render(request, 'studentfood/html/detail_recipe/product.html', context)


@login_required
def favourite_add(request, recipe_id):
    if request.method == 'POST':
        request.user.bookmark_set.create(added_recipe=get_object_or_404(Recipe, pk=recipe_id), user_added=request.user)
    return redirect('studentfood:detail', recipe_id)


def profile(request):  # пользовательские данные (при переходе возвращает объект пользователя)
    recipes_list = Recipe.objects.order_by()
    favorite_list = request.user.bookmark_set.all()
    recipe_form = RecipeForm()
    cp_form = ChangePasswordForm()
    change_photo_form = ChangePhotoForm()

    # Создание рецепта
    if request.method == 'POST':
        recipe_form = RecipeForm(request.POST)
        post_recipe = Recipe()
        if recipe_form.is_valid():
            post_recipe.recipe_name = recipe_form.cleaned_data.get("recipe_name")
            post_recipe.description = recipe_form.cleaned_data.get("description")
            post_recipe.price = recipe_form.cleaned_data.get("price")
            post_recipe.user = request.user
            post_recipe.category = recipe_form.cleaned_data.get("category")
            if 'photo' in request.FILES:  # проверка на то, есть ли в реквесте фотки
                post_recipe.photo = request.FILES['photo']  # если есть, то присваиваем сохраняемому рецепту
            post_recipe.save()
            recipe_form.clean()

    # Смена пароля

    context = {'recipes_list': recipes_list,
               'recipe_form': recipe_form,
               'cp_form': cp_form,
               'favorite_list': favorite_list,
               'change_photo_form': change_photo_form,
              }
    return render(request, 'studentfood/html/profiles/profile.html', context)


def change_password(request):
    if request.method == 'POST':
        cp_user = request.user
        cp_form = ChangePasswordForm(request.POST)
        if cp_form.is_valid():
            cp_user.set_password(cp_form.cleaned_data.get("password"))
            cp_user.save()
    return redirect('studentfood:main')


def change_photo(request):
    if request.method == 'POST':
        change_photo_user = request.user
        change_photo_form = ChangePhotoForm(request.POST)
        if change_photo_form.is_valid():
            if 'photo' in request.FILES:
                change_photo_user.photo = request.FILES['photo']
                change_photo_user.save()
    return redirect('studentfood:profile')


def remove_recipe(request, recipe_id):
    if request.method == 'POST':
        edit_recipe = Recipe.objects.get(pk=recipe_id)
        edit_recipe.is_removed = True
        edit_recipe.save()
    return redirect('studentfood:main')

studentfood/templates/studentfood/html/detail_recipe/detail.html
{% extends 'studentfood/html/base.html' %}{% load static%}
{% load crispy_forms_tags %}
{% block title %}Рецепты для студентов{% endblock %}
{% block stat%}
    <link href="{% static "css/detail.css" %}" rel="stylesheet" type="text/css">
    <link href="{% static "css/star_rating.css" %}" rel="stylesheet" type="text/css">
{% endblock %}

{% block main %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-2">
                <div>
                    <img src="{{ recipe_detail.photo_url }}" width="200" height="200" alt="Технические неполадки">
                </div>
                <div class="favorite-input">
                    <form action="{% url 'studentfood:favourite_add' recipe_detail.id %}" method="post">
                    {% csrf_token %}
                    <input type="submit" value="Добавить в избранное" name="favourite_click">
                    </form>
                </div>
            </div>

            <div class="col-10">
                <h6>{{ recipe_detail.user }} : {{ recipe_detail.pub_date|date:"d.m.Y" }}</h6>
                <h1>{{ recipe_detail.recipe_name }}</h1>
                <p>{{ recipe_detail.description }}</p>
            </div>
        </div>

        <div class="row">
            <div class="col-2"></div>

            <div class="col-8">
                <div class="rating rating_set">
                  <div class="rating_body">
                      <div class="rating_active"></div>
                      <div class="rating_items">
                          <input type="radio" class="rating_item" value="1" name="rating">
                          <input type="radio" class="rating_item" value="2" name="rating">
                          <input type="radio" class="rating_item" value="3" name="rating">
                          <input type="radio" class="rating_item" value="4" name="rating">
                          <input type="radio" class="rating_item" value="5" name="rating">
                      </div>
                  </div>
                  <div class="rating_value">{{ recipe_detail.calculate_mark }}</div>
                </div>
                <br>
                <div>
                    <form action="" method="post">
                    {% csrf_token %}
                    {{ mark_form.as_p }}
                    <input type="submit" value="Поставить оценку!">
                    </form>
                </div>
                <br>
                <div class="row">
                    <p>
                        <strong>Комментарии:</strong>
                        <span>{{ comments_count }}</span>
                    </p>
                    {% for comment in comment_list %}
                            <div class="comment-obj">
                                <p><strong>{{ comment.user }}</strong> | Опубликовано: {{ comment.pub_date|date:"d-m-Y H:i" }}</p>
                                <p>{{ comment.text }}</p>
                            </div>
                        {% empty %}
                            <p>Нет комментариев. Будь первым!</p>
                    {% endfor %}

                    {% if request.user.is_authenticated %}
                                {% if post_comment %}
                                    <h2>Ваш комментарий добавлен!</h2>
                                {% else %}
                                    <h2>Добавить комментарий</h2>
                                    <form action="." method="post">
                                        {% csrf_token %}
                                        {{ comment_form.as_p }}
                                        <p><input type="submit" value="Отправить"></p>
                                    </form>
                                {% endif %}
                    {% endif %}
                </div>
            </div>

            <div class="col-2"></div>
        </div>
    </div>
{% endblock %}

{% block java %}
    <script type="text/javascript" src={% static "js/rating.js" %}></script>
{% endblock %}

studentfood/templates/studentfood/html/detail_recipe/product.html
{% extends 'studentfood/html/base.html' %}{% load static%}
{% load crispy_forms_tags %}
{% block title %}Рецепты для студентов{% endblock %}
{% block stat%}
    <link href="{% static "css/product.css" %}" rel="stylesheet" type="text/css">
    <link href="{% static "css/star_rating.css" %}" rel="stylesheet" type="text/css">
{% endblock %}

{% block main %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-2">
                <div>
                    <img src="{{ recipe_detail.photo_url }}" width="200" height="200" alt="Технические неполадки">
                </div>
                <div class="favorite-input">
                    {% if request.user.is_authenticated and request.user.id not in bookmark_user_ids%}
                    <form action="{% url 'studentfood:favourite_add' recipe_detail.id %}" method="post">
                    {% csrf_token %}
                        <input class="btn btn-info" type="submit" value="Добавить в избранное" name="favourite_click">
                    </form>

                {% endif %}

                </div>
            </div>

            <div class="col-10">
                <h6>{{ recipe_detail.user }} : {{ recipe_detail.pub_date|date:"d.m.Y" }}</h6>
                <h1>{{ recipe_detail.recipe_name }}</h1>
                <p>{{ recipe_detail.description }}</p>
            </div>
        </div>

        <div class="row">
            <div class="col-2"></div>

            <div class="col-8">
                <div class="rating rating_set">
                  <div class="rating_body">
                      <div class="rating_active"></div>
                      <div class="rating_items">
                          <input type="radio" class="rating_item" value="1" name="rating">
                          <input type="radio" class="rating_item" value="2" name="rating">
                          <input type="radio" class="rating_item" value="3" name="rating">
                          <input type="radio" class="rating_item" value="4" name="rating">
                          <input type="radio" class="rating_item" value="5" name="rating">
                      </div>
                  </div>
                  <div class="rating_value">{{ recipe_detail.calculate_mark }}</div>
                </div>
                <br>
                <div>
                    {% if request.user.is_authenticated %}
                <form action="" method="post">
                    {% csrf_token %}
                    {{ mark_form.as_p }}
                    <input class="btn btn-success" type="submit" value="Поставить оценку!">
                </form>
                    {% else %}
                    <p>Войдите в систему, чтобы поставить оценку.</p>
                {% endif %}
                </div>
                <br>
                <div class="row">
                    <p>
                        <strong>Комментарии:</strong>
                        <span>{{ comments_count }}</span>
                    </p>
                    {% for comment in comment_list %}
                            <div class="comment-obj">
                                <p><strong>{{ comment.user }}</strong> | Опубликовано: {{ comment.pub_date|date:"d-m-Y H:i" }}</p>
                                <p>{{ comment.text }}</p>
                            </div>
                        {% empty %}
                            <p>Нет комментариев. Будь первым!</p>
                    {% endfor %}

                    {% if request.user.is_authenticated %}
                                {% if post_comment %}
                                    <h2>Ваш комментарий добавлен!</h2>
                                {% else %}
                                    <h2>Добавить комментарий</h2>
                                    <form action="." method="post">
                                        {% csrf_token %}
                                        {{ comment_form.as_p }}
                                        <p><input class="btn btn-primary" type="submit" value="Отправить"></p>
                                    </form>
                                {% endif %}
                    {% endif %}
                </div>
            </div>

            <div class="col-2"></div>
        </div>
    </div>
{% endblock %}

{% block java %}
    <script type="text/javascript" src={% static "js/rating.js" %}></script>
{% endblock %}